services:
  # docker run -d -p 8080:8080 -p 8081:8081 -p 3000:3000 openfga/openfga run
  openfga:
    image: openfga/openfga
    command: run
    ports:
      - 8080:8080
      - 8081:8081
      - 3000:3000
