on:
  workflow_call: null
jobs:
  empty-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "can remove when there's other jobs"
  new:
    uses: this-org/this-repo/services/api/.github/workflows
